version: "3.3"
   
services:
  streambot:
    image: stream:latest
    build: .
    command: bash start.sh
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 100M
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 1
        window: 120s
      replicas: 1